---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: renovate-secret
    template:
      data:
        GITHUB_APP_CLIENT_ID: '{{ .GITHUB_APP_CLIENT_ID }}'
        GITHUB_APP_PRIVATE_KEY: '{{ .GITHUB_APP_PRIVATE_KEY }}'
        GITHUB_APP_INSTALLATION_ID: '{{ .GITHUB_APP_INSTALLATION_ID }}'
  dataFrom:
    - extract:
        key: github
