---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renovate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: warn
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: 'OnRootMismatch'
        runAsUser: 12021
        runAsGroup: 1000
        runAsNonRoot: true

    controllers:
      *app :
        type: cronjob

        cronjob:
          schedule: '@hourly'
          backoffLimit: 0
          concurrencyPolicy: Forbid
          failedJobsHistory: 1
          successfulJobsHistory: 1

        pod:
          restartPolicy: Never

        initContainers:
          token:
            image:
              repository: ghcr.io/tholinka/github-app-token
              tag: 3.21.0@sha256:ccf6b422258a74d6ae7472a116c508f5e4486bfc15905ea0b2b82fabcea98549
            env:
              TOKEN_DIR: /token
              TOKEN_ENV_NAME: RENOVATE_TOKEN
            envFrom:
              - secretRef:
                  name: renovate-secret
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 25Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          app:
            image:
              repository: ghcr.io/renovatebot/renovate
              tag: 39.240.1
            env:
              LOG_LEVEL: debug
              RENOVATE_AUTODISCOVER: 'true'
              RENOVATE_REPOSITORY_CACHE: true
              RENOVATE_CACHE_DIR: /cache
              RENOVATE_CACHE_PRIVATE_PACKAGES: 'true'
              RENOVATE_PLATFORM: github
              RENOVATE_PLATFORM_COMMIT: 'true'
            envFrom:
              - secretRef:
                  name: renovate-secret
            resources:
              requests:
                cpu: 1
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              # capabilities: # tries to chown the tools it installs to /tmp
              #   drop:
              #     - ALL

    persistence:
      cache:
        type: persistentVolumeClaim
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 5Gi
      token:
        type: emptyDir
        advancedMounts:
          *app :
            token:
              - path: /token
            app:
              - path: /usr/local/env.d
                subPath: env.d
      tmp:
        type: emptyDir
